###
# Список товаров

GET http://example.front.ylab.io/api/v1/articles

###
# Список с пагинацией

GET http://example.front.ylab.io/api/v1/articles?limit=10&skip=20

###
# Список с пагинацией и возвратом общего количества (и только нужных свойств через fields)
# Про формат fields смотри http://query.rest

GET http://example.front.ylab.io/api/v1/articles?limit=10&skip=10&
  fields=items(_id, title, price),count

###
# Товар по id

GET http://example.front.ylab.io/api/v1/articles/65782dc9cbf638685992a34b

###
# Товар по id с подробностями о стране и категории
# Про формат fields смотри http://query.rest

GET http://example.front.ylab.io/api/v1/articles/65782dc9cbf638685992a34b?
  fields=*,madeIn(title,code),category(title)
