###
# Авторизация

POST http://example.front.ylab.io/api/v1/users/sign
Content-Type: application/json

{
  "login": "test_1",
  "password": "123456"
}

###
# Выход - отмена авториазции для удаления токена

DELETE http://example.front.ylab.io/api/v1/users/sign
X-Token: 56677139a343b4c4c8087a3da579e9fabdbccc6231941654b094a4c011a4a582
Content-Type: application/json

###
# Свой профиль

GET http://example.front.ylab.io/api/v1/users/self?fields=*
X-Token: 56677139a343b4c4c8087a3da579e9fabdbccc6231941654b094a4c011a4a582
Content-Type: application/json
