name: Build Test
env:
  VERCEL_ORG_ID: team_nuZTpjMFtjg6nYvRq8D59qS1
  VERCEL_PROJECT_ID: prj_DjaAeRmIZ6Nsl8pNbWl8YftMgHbO
on:
  pull_request:
    branches:
      - lecture-1
      - lecture-2
      - lecture-3
      - lecture-4
      - lecture-5
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install CLI
        run: npm install --global vercel@latest

      - name: Pull Environments
<<<<<<< HEAD
        run: vercel pull --yes --environment=preview --token=cjMB7gUOQfIZC8XoUZALg9fI

      - name: Build
        run: vercel build --token=cjMB7gUOQfIZC8XoUZALg9fI

      - name: Deploy
        run: vercel deploy --prebuilt --token=cjMB7gUOQfIZC8XoUZALg9fI
=======
        run: vercel pull --yes --environment=preview --token=YaPgLKFawGp2uztyfu4QOcOh

      - name: Build
        run: vercel build --token=YaPgLKFawGp2uztyfu4QOcOh

      - name: Deploy
        run: vercel deploy --prebuilt --token=YaPgLKFawGp2uztyfu4QOcOh
>>>>>>> 6aee3f6 (fix ci)
